# Generated by Django 4.2.6 on 2024-03-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleservice',
            old_name='vehicle_service',
            new_name='vehicle_part',
        ),
    ]
