# Generated by Django 4.2.6 on 2024-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_vehicle_service_vehicleservice_vehicle_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleservice',
            name='vehicle_next_service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicleservice',
            name='vehicle_previous_service_date',
            field=models.DateField(),
        ),
    ]
