# Generated by Django 4.2.6 on 2024-01-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='name',
        ),
        migrations.AddField(
            model_name='subservice',
            name='subservice_name',
            field=models.CharField(choices=[('Oil change', 'Oil change'), ('Fluid checks', 'Fluid checks'), ('Tire rotation', 'Tire rotation'), ('Battery inspection', 'Battery inspection'), ('Engine diagnostics', 'Engine diagnostics'), ('Computerized vehicle inspection', 'Computerized vehicle inspection'), ('Brake pad replacement', 'Brake pad replacement'), ('Brake fluid flush', 'Brake fluid flush'), ('Brake system inspection', 'Brake system inspection'), ('Tire replacement', 'Tire replacement'), ('Wheel alignment', 'Wheel alignment'), ('Tire balancing', 'Tire balancing'), ('Exhaust system repair', 'Exhaust system repair'), ('Catalytic converter replacement', 'Catalytic converter replacement'), ('Transmission fluid change', 'Transmission fluid change'), ('Transmission system inspection and repair', 'Transmission system inspection and repair'), ('Battery replacement', 'Battery replacement'), ('Alternator repair', 'Alternator repair'), ('Radiator flush', 'Radiator flush'), ('Thermostat replacement', 'Thermostat replacement'), ('A/C recharge', 'A/C recharge'), ('A/C system inspection and repair', 'A/C system inspection and repair'), ('Fuel injector cleaning', 'Fuel injector cleaning'), ('Fuel filter replacement', 'Fuel filter replacement'), ('Shock and strut replacement', 'Shock and strut replacement'), ('Power steering fluid flush', 'Power steering fluid flush'), ('Engine tune-up', 'Engine tune-up'), ('Timing belt replacement', 'Timing belt replacement'), ('State vehicle inspections', 'State vehicle inspections'), ('General safety inspections', 'General safety inspections'), ('Comprehensive vehicle checkups', 'Comprehensive vehicle checkups')], default=None, max_length=100),
        ),
    ]
