# Generated by Django 4.2.6 on 2024-01-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subservice_name_subservice_subservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='service_type',
            field=models.ForeignKey(limit_choices_to={'service_type__in': ['Oil change', 'Fluid checks', 'Tire rotation', 'Battery inspection', 'Engine diagnostics', 'Computerized vehicle inspection', 'Brake pad replacement', 'Brake fluid flush', 'Brake system inspection', 'Tire replacement', 'Wheel alignment', 'Tire balancing', 'Exhaust system repair', 'Catalytic converter replacement', 'Transmission fluid change', 'Transmission system inspection and repair', 'Battery replacement', 'Alternator repair', 'Radiator flush', 'Thermostat replacement', 'A/C recharge', 'A/C system inspection and repair', 'Fuel injector cleaning', 'Fuel filter replacement', 'Shock and strut replacement', 'Power steering fluid flush', 'Engine tune-up', 'Timing belt replacement', 'State vehicle inspections', 'General safety inspections', 'Comprehensive vehicle checkups']}, on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
        ),
    ]
