# Generated by Django 4.2.6 on 2024-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vehicleservice_vehicle_next_service_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_body',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_chassis_frame',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_fuel_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_gross_weight',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_load_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_passengers_capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_reg_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_tare_weight',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_tax_class',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=40),
        ),
    ]
