# Generated by Django 4.2.6 on 2024-03-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_subservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
        ),
    ]
